# -*- coding: utf-8 -*-
"""check.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14Id_icyyINIETgVk-olMaZtO9mm6ls01
"""

# Commented out IPython magic to ensure Python compatibility.
# %pwd

cd /content/drive/MyDrive/dataset/input/

ls

import numpy as np
import pandas as pd
import os
import random 
import shutil
import cv2
import csv
import zipfile
import glob

outdir =  '/content/drive/MyDrive/dataset/input/train/pneumonia/'
out_list = [os.path.basename(x) for x in glob.glob(outdir + './*.png')]
#print(out_list)
print(len(out_list))

outdir = '/content/drive/MyDrive/dataset/input/train/normal/'
out_list = [os.path.basename(x) for x in glob.glob(outdir + './*.png')]
#print(out_list)
print(len(out_list))

outdir = '/content/drive/MyDrive/dataset/input/test/pneumonia/'
out_list = [os.path.basename(x) for x in glob.glob(outdir + './*.png')]
#print(out_list)
print(len(out_list))

outdir = '/content/drive/MyDrive/dataset/input/test/normal/'
out_list = [os.path.basename(x) for x in glob.glob(outdir + './*.png')]
#print(out_list)
print(len(out_list))

train_dir = '../input/train'
test_dir =  '../input/test'

#X = []
#Y = []

#Loop through the training and test folders, as well as the 'NORMAL' and 'PNEUMONIA' subfolders 
#and append all images into array X.  Append the classification (0 or 1) into array Y.

for fileName in os.listdir(train_dir + "/normal"): 
        img = (train_dir + "/normal/" + fileName)
        print(img)